openapi: 3.1.0
# openapi: 3.0.3  - запасний варік для перевірки в https://editor.swagger.io/
info:
  version: 1.0.0
  title: Contacts web app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for contact management with authorization
tags:
  # теги, що ви будете використовувати
  - name: Contacts
    description: Contact operations
  - name: Auth
    description: Authorization and registration
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-q3zf.onrender.com
paths:
  # посилання на ендпоінти
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml

  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml

  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer